### ISSUE TITLE
Disallow duplicate requests to the same host for the same dates

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#2998]
Our system should not allow users to send multiple request to the same user for the same days. This happened to me and it ruined my response rate score, not to mention clogged my email with notifications:

![image](https://user-images.githubusercontent.com/79384268/173086809-41a575f0-b1b8-472b-91a3-414845a73b8c.png)

**Comment by jesseallhands** [comment]
this was a weird bug that should be resolved now

**Comment by nc225** [comment]
FYI this bug is not resolved, I have found multiple similar cases recently.

**Comment by aapeliv** [comment]
we discussed this at length earlier and arrived at not allowing duplicate requests on overlapping dates within 3 hours of the last such request, which was implemented in https://github.com/Couchers-org/couchers/pull/9339

if this is somehow still a concern, we can discuss first elsewhere before opening an issue
