### ISSUE TITLE
Issues with latest versions of grpcio

### ISSUE THREAD

**Issue by Rohlik** [Couchers-org/couchers#3962]
See no messages or host requests. I see error: _"Couldn't connect to the server. Please check your Internet connection or try again later."_ instead.
Of course, my internet is excellent as I'm able to send this bug report.
**This is serious bug** as it's impossible to continue with conversation on outgoing requests, etc.

**Comment by aapeliv** [comment]
Should be fixed for the time being.

**Comment by Gelmo** [comment]
This particular issue persists for me and I am unable to create an account as a result. A 503 error occurs when POSTing to https://couchers.org/api/org.couchers.auth.Auth/SignupFlow

**Comment by aapeliv** [comment]
Okay, thanks @Gelmo. I'm looking into it.

**Comment by aapeliv** [comment]
This seems to have started being a problem since the last deploy of 92d79160 on 2024-02-10 23:50:36 UTC. Before that it was running 39bd5b85. https://github.com/Couchers-org/couchers/compare/39bd5b8594f78345b625f02ed9ada9c31a74af01..92d791605f854a750d3afbd374f3fe86005d0805

**Comment by Gelmo** [comment]
Looks like some of the other recent issues are related, as well.

**Comment by aapeliv** [comment]
Have not been able to find the root cause. It works again after restarting. The issue is probably in grpc+envoy. I've enabled some more stats for envoy and will try to look more when it crashes again...

**Comment by Rohlik** [comment]
I still sometimes see the same errors, but overall the platform is in better shape then it was 3 days ago.
![image](https://github.com/Couchers-org/couchers/assets/2051154/f64cea4b-90ee-4457-9585-1d4058469902)

**Comment by aapeliv** [comment]
I think this commit might have caused it: https://github.com/Couchers-org/couchers/commit/3801ba6a3937882ccd84fc862ee8d714f925ce20

It's not a full fix, but I've tried to revert it for now, to see if that helps.

**Comment by Rohlik** [comment]
Seems fixed to me, no more errors.

**Comment by aapeliv** [comment]
OK, so the latest versions of grpcio are somehow causing issues.

**Comment by aapeliv** [comment]
Trying to debug on next here: https://github.com/Couchers-org/couchers/tree/next-grpc-testing

**Comment by aapeliv** [comment]
API call logs:

```
     version      | count |   min    |   max    | perf_reports 
------------------+-------+----------+----------+--------------
 develop-d0ecbeed | 34847 | 43579058 | 43613904 |         1702 -- working grpc v1.56.2
 develop-4b8be451 | 47428 | 43531630 | 43579057 |         2366 -- working grpc v1.56.0
 develop-282046b5 | 36060 | 43495570 | 43531629 |         1780 -- working grpc v1.55.0
 develop-ffa8d5b2 | 16074 | 43479496 | 43495569 |          826 -- broken grpc v1.57.0
 develop-192eb3bb |    41 | 43479455 | 43479495 |            5 -- upgraded other deps/working grpc v1.54.2
 develop-ae98ece4 |   223 | 43479232 | 43479454 |           11 -- donations botched/working grpc v1.54.2
 develop-4e87f4c0 | 39609 | 43439623 | 43479231 |         1947 -- downgraded grpc (v1.54.2)
 develop-f9dd87ad |  8332 | 43431291 | 43439622 |          420 -- broken grpc (v1.62.1)
 develop-8c664ae7 | 99253 | 43332038 | 43431290 |         4902 -- broken grpc (v1.62.1)
 develop-fb657685 | 16754 | 43315284 | 43332037 |          847 -- old version
 develop-921b768a | 31899 | 43283385 | 43315283 |         1557 -- old version
 develop-42917530 | 99456 | 43183929 | 43283384 |         4871 -- old version

```

**Comment by aapeliv** [comment]
I guess the issue is somewhere between [1.54.2](https://github.com/grpc/grpc/releases/tag/v1.54.2) (May 10, 2023) and [1.59.3](https://github.com/grpc/grpc/releases/tag/v1.59.3) (Nov 17, 2023)...

**Comment by aapeliv** [comment]
* v1.57.0 failed in ~8 hours
* v1.55.0 did not fail for ~20 hours
* v1.56.0 did not fail for ~27 hours
* v1.56.2 is currently in prod

**Comment by aapeliv** [comment]
v1.56.2 has been in prod for 57 hours or so without issues. I upgraded some other stuff 32 hours ago, but it seems fine for now.

**Comment by aapeliv** [comment]
I've gone through the grpc [commit history between these two versions](https://github.com/grpc/grpc/compare/v1.56.2...v1.57.0) and I'm not seeing anything that really glares out as being problematic...

**Comment by aapeliv** [comment]
This seems once again to be working fine now. We've been running the latest version in prod for a while and had no issues. I also upgraded envoy which might have helped!
